name: zookeeper # Name of the Catalog Entry
description: |
  # Description of the Catalog Entry
version: 3.4.9-rancher1 # Version of the Catalog to be used
category: # Category to be used for searching catalog entries
maintainer: # The maintainer of the catalog entry
license: # The license
projectURL: # A URL related to the catalog entry
